### ISSUE TITLE
JSON.parse error

### ISSUE THREAD

**Issue by akisvolanis** [pmdroid/yeelight-wifi#16]
Sometimes when i try to change hue/saturation/brightness and power it throws that error: 
```
undefined:2
{"method":"props","params":{"power":"on"}}
^

SyntaxError: Unexpected token { in JSON at position 27
    at JSON.parse (<anonymous>)
    at Yeelight.formatResponse (/home/pi/Workspace/home-automation-server/node_modules/yeelight-wifi/build/Yeelight.js:153:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
```

For all cases in the same line Yeelight.js:153. Any ideas?

**Comment by akisvolanis** [comment]
Fixed my issue by changing `_this.socket.on('data', _this.formatResponse.bind(_this));` on line 83 to  `_this.socket.on('end', _this.formatResponse.bind(_this));` according to [this](https://nodejs.org/api/stream.html#stream_class_stream_readable).  Parsing chunk of data as JSON seems to be corrupt in some cases and it make sense. Thanks.
