### ISSUE TITLE
JSON parse error when get values

### ISSUE THREAD

**Issue by NickDub-old** [pmdroid/yeelight-wifi#75]
When I try to get values : 
```javascript
yeelight.getValues('power', 'bright', 'hue', 'sat')
	.then((result) => {
		console.log(`${result} - ${JSON.stringify(result)}`);
	});
```

I've this error : 
```
SyntaxError: Unexpected token { in JSON at position 25
    at JSON.parse (<anonymous>)
    at Yeelight.formatResponse (/home/pi/gladys/api/hooks/yeelight2/node_modules/yeelight-wifi/build/Yeelight.js:154:25)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```
and result value is undefined.

**Comment by NickDub-old** [comment]
Seems to be resolved in issues #16 and #32.
